services:
  postgres:
    image: postgres:16

    container_name: neurohabit-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPostgres123
      POSTGRES_DB: neurohabit

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: